language: python

python:
  - "3.6"

install:
  - pip install -r ./src/requirements.txt

script:
  - cd src/fetchFunction && pytest 
  - npm install -g serverless
  - cd src/fetchFunction && sls deploy