version: 0.1
phases:
  install:
    commands:
      - pip install -r ./src/requirements.txt
      - cd src/fetchFunction && pytest
      - npm install -g serverless
      - cd src && npm install
  build:
    commands:
      - cd src && sls deploy